# Generated by Django 3.2.6 on 2021-11-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_todo_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
